-- ============================================================
-- 客户-理财顾问关联分配
-- 根据客户等级匹配相应级别的理财顾问
-- ============================================================

USE wealth_butler;

-- 在 fin_customer_profile 表中添加 advisor_id 字段（如果不存在）
-- 检查字段是否存在，不存在才添加
SET @exist := (SELECT COUNT(*) FROM information_schema.COLUMNS
               WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='fin_customer_profile' AND COLUMN_NAME='advisor_id');
SET @sqlstmt := IF(@exist = 0,
    'ALTER TABLE `fin_customer_profile` ADD COLUMN `advisor_id` INT COMMENT ''负责理财顾问ID'' AFTER `customer_id`, ADD INDEX `idx_advisor_id` (`advisor_id`)',
    'SELECT ''advisor_id already exists'' AS message');
PREPARE stmt FROM @sqlstmt;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

-- 更新客户画像表，分配理财顾问
UPDATE `fin_customer_profile` SET `advisor_id` = 202 WHERE `customer_id` = 1;
UPDATE `fin_customer_profile` SET `advisor_id` = 216 WHERE `customer_id` = 2;
UPDATE `fin_customer_profile` SET `advisor_id` = 204 WHERE `customer_id` = 3;
UPDATE `fin_customer_profile` SET `advisor_id` = 203 WHERE `customer_id` = 4;
UPDATE `fin_customer_profile` SET `advisor_id` = 203 WHERE `customer_id` = 5;
UPDATE `fin_customer_profile` SET `advisor_id` = 217 WHERE `customer_id` = 6;
UPDATE `fin_customer_profile` SET `advisor_id` = 204 WHERE `customer_id` = 7;
UPDATE `fin_customer_profile` SET `advisor_id` = 216 WHERE `customer_id` = 8;
UPDATE `fin_customer_profile` SET `advisor_id` = 203 WHERE `customer_id` = 9;
UPDATE `fin_customer_profile` SET `advisor_id` = 203 WHERE `customer_id` = 10;
UPDATE `fin_customer_profile` SET `advisor_id` = 217 WHERE `customer_id` = 11;
UPDATE `fin_customer_profile` SET `advisor_id` = 216 WHERE `customer_id` = 12;
UPDATE `fin_customer_profile` SET `advisor_id` = 216 WHERE `customer_id` = 13;
UPDATE `fin_customer_profile` SET `advisor_id` = 204 WHERE `customer_id` = 14;
UPDATE `fin_customer_profile` SET `advisor_id` = 217 WHERE `customer_id` = 15;
UPDATE `fin_customer_profile` SET `advisor_id` = 216 WHERE `customer_id` = 16;
UPDATE `fin_customer_profile` SET `advisor_id` = 216 WHERE `customer_id` = 17;
UPDATE `fin_customer_profile` SET `advisor_id` = 203 WHERE `customer_id` = 18;
UPDATE `fin_customer_profile` SET `advisor_id` = 203 WHERE `customer_id` = 19;
UPDATE `fin_customer_profile` SET `advisor_id` = 203 WHERE `customer_id` = 20;
UPDATE `fin_customer_profile` SET `advisor_id` = 216 WHERE `customer_id` = 21;
UPDATE `fin_customer_profile` SET `advisor_id` = 203 WHERE `customer_id` = 22;
UPDATE `fin_customer_profile` SET `advisor_id` = 203 WHERE `customer_id` = 23;
UPDATE `fin_customer_profile` SET `advisor_id` = 203 WHERE `customer_id` = 24;
UPDATE `fin_customer_profile` SET `advisor_id` = 204 WHERE `customer_id` = 25;
UPDATE `fin_customer_profile` SET `advisor_id` = 202 WHERE `customer_id` = 26;
UPDATE `fin_customer_profile` SET `advisor_id` = 202 WHERE `customer_id` = 27;
UPDATE `fin_customer_profile` SET `advisor_id` = 217 WHERE `customer_id` = 28;
UPDATE `fin_customer_profile` SET `advisor_id` = 216 WHERE `customer_id` = 29;
UPDATE `fin_customer_profile` SET `advisor_id` = 202 WHERE `customer_id` = 30;
UPDATE `fin_customer_profile` SET `advisor_id` = 216 WHERE `customer_id` = 31;
UPDATE `fin_customer_profile` SET `advisor_id` = 204 WHERE `customer_id` = 32;
UPDATE `fin_customer_profile` SET `advisor_id` = 203 WHERE `customer_id` = 33;
UPDATE `fin_customer_profile` SET `advisor_id` = 203 WHERE `customer_id` = 34;
UPDATE `fin_customer_profile` SET `advisor_id` = 203 WHERE `customer_id` = 35;
UPDATE `fin_customer_profile` SET `advisor_id` = 203 WHERE `customer_id` = 36;
UPDATE `fin_customer_profile` SET `advisor_id` = 204 WHERE `customer_id` = 37;
UPDATE `fin_customer_profile` SET `advisor_id` = 203 WHERE `customer_id` = 38;
UPDATE `fin_customer_profile` SET `advisor_id` = 203 WHERE `customer_id` = 39;
UPDATE `fin_customer_profile` SET `advisor_id` = 217 WHERE `customer_id` = 40;
UPDATE `fin_customer_profile` SET `advisor_id` = 216 WHERE `customer_id` = 41;
UPDATE `fin_customer_profile` SET `advisor_id` = 202 WHERE `customer_id` = 42;
UPDATE `fin_customer_profile` SET `advisor_id` = 204 WHERE `customer_id` = 43;
UPDATE `fin_customer_profile` SET `advisor_id` = 203 WHERE `customer_id` = 44;
UPDATE `fin_customer_profile` SET `advisor_id` = 216 WHERE `customer_id` = 45;
UPDATE `fin_customer_profile` SET `advisor_id` = 216 WHERE `customer_id` = 46;
UPDATE `fin_customer_profile` SET `advisor_id` = 204 WHERE `customer_id` = 47;
UPDATE `fin_customer_profile` SET `advisor_id` = 216 WHERE `customer_id` = 48;
UPDATE `fin_customer_profile` SET `advisor_id` = 217 WHERE `customer_id` = 49;
UPDATE `fin_customer_profile` SET `advisor_id` = 216 WHERE `customer_id` = 50;
UPDATE `fin_customer_profile` SET `advisor_id` = 217 WHERE `customer_id` = 51;
UPDATE `fin_customer_profile` SET `advisor_id` = 203 WHERE `customer_id` = 52;
UPDATE `fin_customer_profile` SET `advisor_id` = 216 WHERE `customer_id` = 53;
UPDATE `fin_customer_profile` SET `advisor_id` = 216 WHERE `customer_id` = 54;
UPDATE `fin_customer_profile` SET `advisor_id` = 202 WHERE `customer_id` = 55;
UPDATE `fin_customer_profile` SET `advisor_id` = 203 WHERE `customer_id` = 56;
UPDATE `fin_customer_profile` SET `advisor_id` = 217 WHERE `customer_id` = 57;
UPDATE `fin_customer_profile` SET `advisor_id` = 216 WHERE `customer_id` = 58;
UPDATE `fin_customer_profile` SET `advisor_id` = 204 WHERE `customer_id` = 59;
UPDATE `fin_customer_profile` SET `advisor_id` = 202 WHERE `customer_id` = 60;
UPDATE `fin_customer_profile` SET `advisor_id` = 217 WHERE `customer_id` = 61;
UPDATE `fin_customer_profile` SET `advisor_id` = 202 WHERE `customer_id` = 62;
UPDATE `fin_customer_profile` SET `advisor_id` = 204 WHERE `customer_id` = 63;
UPDATE `fin_customer_profile` SET `advisor_id` = 216 WHERE `customer_id` = 64;
UPDATE `fin_customer_profile` SET `advisor_id` = 204 WHERE `customer_id` = 65;
UPDATE `fin_customer_profile` SET `advisor_id` = 217 WHERE `customer_id` = 66;
UPDATE `fin_customer_profile` SET `advisor_id` = 202 WHERE `customer_id` = 67;
UPDATE `fin_customer_profile` SET `advisor_id` = 204 WHERE `customer_id` = 68;
UPDATE `fin_customer_profile` SET `advisor_id` = 204 WHERE `customer_id` = 69;
UPDATE `fin_customer_profile` SET `advisor_id` = 203 WHERE `customer_id` = 70;
UPDATE `fin_customer_profile` SET `advisor_id` = 216 WHERE `customer_id` = 71;
UPDATE `fin_customer_profile` SET `advisor_id` = 202 WHERE `customer_id` = 72;
UPDATE `fin_customer_profile` SET `advisor_id` = 217 WHERE `customer_id` = 73;
UPDATE `fin_customer_profile` SET `advisor_id` = 204 WHERE `customer_id` = 74;
UPDATE `fin_customer_profile` SET `advisor_id` = 204 WHERE `customer_id` = 75;
UPDATE `fin_customer_profile` SET `advisor_id` = 216 WHERE `customer_id` = 76;
UPDATE `fin_customer_profile` SET `advisor_id` = 217 WHERE `customer_id` = 77;
UPDATE `fin_customer_profile` SET `advisor_id` = 202 WHERE `customer_id` = 78;
UPDATE `fin_customer_profile` SET `advisor_id` = 217 WHERE `customer_id` = 79;
UPDATE `fin_customer_profile` SET `advisor_id` = 217 WHERE `customer_id` = 80;
UPDATE `fin_customer_profile` SET `advisor_id` = 202 WHERE `customer_id` = 81;
UPDATE `fin_customer_profile` SET `advisor_id` = 202 WHERE `customer_id` = 82;
UPDATE `fin_customer_profile` SET `advisor_id` = 216 WHERE `customer_id` = 83;
UPDATE `fin_customer_profile` SET `advisor_id` = 203 WHERE `customer_id` = 84;
UPDATE `fin_customer_profile` SET `advisor_id` = 204 WHERE `customer_id` = 85;
UPDATE `fin_customer_profile` SET `advisor_id` = 202 WHERE `customer_id` = 86;
UPDATE `fin_customer_profile` SET `advisor_id` = 203 WHERE `customer_id` = 87;
UPDATE `fin_customer_profile` SET `advisor_id` = 216 WHERE `customer_id` = 88;
UPDATE `fin_customer_profile` SET `advisor_id` = 202 WHERE `customer_id` = 89;
UPDATE `fin_customer_profile` SET `advisor_id` = 203 WHERE `customer_id` = 90;
UPDATE `fin_customer_profile` SET `advisor_id` = 204 WHERE `customer_id` = 91;
UPDATE `fin_customer_profile` SET `advisor_id` = 217 WHERE `customer_id` = 92;
UPDATE `fin_customer_profile` SET `advisor_id` = 205 WHERE `customer_id` = 93;
UPDATE `fin_customer_profile` SET `advisor_id` = 205 WHERE `customer_id` = 94;
UPDATE `fin_customer_profile` SET `advisor_id` = 205 WHERE `customer_id` = 95;
UPDATE `fin_customer_profile` SET `advisor_id` = 217 WHERE `customer_id` = 96;
UPDATE `fin_customer_profile` SET `advisor_id` = 217 WHERE `customer_id` = 97;
UPDATE `fin_customer_profile` SET `advisor_id` = 217 WHERE `customer_id` = 98;
UPDATE `fin_customer_profile` SET `advisor_id` = 202 WHERE `customer_id` = 99;
UPDATE `fin_customer_profile` SET `advisor_id` = 202 WHERE `customer_id` = 100;
UPDATE `fin_customer_profile` SET `advisor_id` = 201 WHERE `customer_id` = 101;
UPDATE `fin_customer_profile` SET `advisor_id` = 202 WHERE `customer_id` = 102;
UPDATE `fin_customer_profile` SET `advisor_id` = 205 WHERE `customer_id` = 103;
UPDATE `fin_customer_profile` SET `advisor_id` = 202 WHERE `customer_id` = 104;
UPDATE `fin_customer_profile` SET `advisor_id` = 201 WHERE `customer_id` = 105;
UPDATE `fin_customer_profile` SET `advisor_id` = 204 WHERE `customer_id` = 106;
UPDATE `fin_customer_profile` SET `advisor_id` = 205 WHERE `customer_id` = 107;
UPDATE `fin_customer_profile` SET `advisor_id` = 204 WHERE `customer_id` = 108;
UPDATE `fin_customer_profile` SET `advisor_id` = 205 WHERE `customer_id` = 109;
UPDATE `fin_customer_profile` SET `advisor_id` = 217 WHERE `customer_id` = 110;
UPDATE `fin_customer_profile` SET `advisor_id` = 202 WHERE `customer_id` = 111;
UPDATE `fin_customer_profile` SET `advisor_id` = 204 WHERE `customer_id` = 112;
UPDATE `fin_customer_profile` SET `advisor_id` = 201 WHERE `customer_id` = 113;
UPDATE `fin_customer_profile` SET `advisor_id` = 204 WHERE `customer_id` = 114;
UPDATE `fin_customer_profile` SET `advisor_id` = 201 WHERE `customer_id` = 115;
UPDATE `fin_customer_profile` SET `advisor_id` = 205 WHERE `customer_id` = 116;
UPDATE `fin_customer_profile` SET `advisor_id` = 201 WHERE `customer_id` = 117;
UPDATE `fin_customer_profile` SET `advisor_id` = 217 WHERE `customer_id` = 118;
UPDATE `fin_customer_profile` SET `advisor_id` = 202 WHERE `customer_id` = 119;
UPDATE `fin_customer_profile` SET `advisor_id` = 201 WHERE `customer_id` = 120;
UPDATE `fin_customer_profile` SET `advisor_id` = 201 WHERE `customer_id` = 121;
UPDATE `fin_customer_profile` SET `advisor_id` = 202 WHERE `customer_id` = 122;
UPDATE `fin_customer_profile` SET `advisor_id` = 217 WHERE `customer_id` = 123;
UPDATE `fin_customer_profile` SET `advisor_id` = 202 WHERE `customer_id` = 124;
UPDATE `fin_customer_profile` SET `advisor_id` = 204 WHERE `customer_id` = 125;
UPDATE `fin_customer_profile` SET `advisor_id` = 204 WHERE `customer_id` = 126;
UPDATE `fin_customer_profile` SET `advisor_id` = 201 WHERE `customer_id` = 127;
UPDATE `fin_customer_profile` SET `advisor_id` = 205 WHERE `customer_id` = 128;
UPDATE `fin_customer_profile` SET `advisor_id` = 201 WHERE `customer_id` = 129;
UPDATE `fin_customer_profile` SET `advisor_id` = 205 WHERE `customer_id` = 130;
UPDATE `fin_customer_profile` SET `advisor_id` = 205 WHERE `customer_id` = 131;
UPDATE `fin_customer_profile` SET `advisor_id` = 205 WHERE `customer_id` = 132;
UPDATE `fin_customer_profile` SET `advisor_id` = 205 WHERE `customer_id` = 133;
UPDATE `fin_customer_profile` SET `advisor_id` = 205 WHERE `customer_id` = 134;
UPDATE `fin_customer_profile` SET `advisor_id` = 205 WHERE `customer_id` = 135;
UPDATE `fin_customer_profile` SET `advisor_id` = 201 WHERE `customer_id` = 136;
UPDATE `fin_customer_profile` SET `advisor_id` = 201 WHERE `customer_id` = 137;
UPDATE `fin_customer_profile` SET `advisor_id` = 201 WHERE `customer_id` = 138;
UPDATE `fin_customer_profile` SET `advisor_id` = 201 WHERE `customer_id` = 139;
UPDATE `fin_customer_profile` SET `advisor_id` = 201 WHERE `customer_id` = 140;
UPDATE `fin_customer_profile` SET `advisor_id` = 205 WHERE `customer_id` = 141;
UPDATE `fin_customer_profile` SET `advisor_id` = 201 WHERE `customer_id` = 142;
UPDATE `fin_customer_profile` SET `advisor_id` = 205 WHERE `customer_id` = 143;
UPDATE `fin_customer_profile` SET `advisor_id` = 205 WHERE `customer_id` = 144;
UPDATE `fin_customer_profile` SET `advisor_id` = 205 WHERE `customer_id` = 145;
UPDATE `fin_customer_profile` SET `advisor_id` = 201 WHERE `customer_id` = 146;
UPDATE `fin_customer_profile` SET `advisor_id` = 201 WHERE `customer_id` = 147;
UPDATE `fin_customer_profile` SET `advisor_id` = 205 WHERE `customer_id` = 148;
UPDATE `fin_customer_profile` SET `advisor_id` = 205 WHERE `customer_id` = 149;
UPDATE `fin_customer_profile` SET `advisor_id` = 201 WHERE `customer_id` = 150;

-- 完成
